apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: development-env
          image: casinowebsite/frontend
          imagePullPolicy: IfNotPresent
          name: frontend
          ports:
            - containerPort: 8080
      restartPolicy: Always
status: {}
