apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend
    spec:
      containers:
          image: casinowebsite/frontend
          imagePullPolicy: IfNotPresent
          name: frontend
          ports:
            - containerPort: 8080
      restartPolicy: Always
status: {}
