apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: casinowebsite/frontend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
      restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
status:
  loadBalancer: {}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-tls-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
spec:
  rules:
    - host: frontend.casino.thibault-cne
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 8080
  tls:
    - secretName: frontend-tls
      hosts:
        - frontend.casino.thibault-cne