version: 3

tasks:
  frontend:
    dir: frontend
    cmds:
      - npm run dev
    silent: true
  
  backend:
    dir: backend
    cmds:
      - docker-compose up -d
      - go run ./cmd/server/main.go
    silent: true
  
  run-dev:
    cmds:
      - task: backend
      - task: frontend
  
  deploy-cert-manager:
    internal: true
    cmds:
      - kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.11.0/cert-manager.yaml
  
  deploy-letsencrypt:
    internal: true
    cmds:
      - kubectl apply -f letsencrypt-prod.yaml
  
  deploy-traefik:
    internal: true
    cmds:
      - kubectl apply -f traefik-https-redirect-middleware.yaml

  build-backend:
    internal: true
    dir: backend
    vars:
      IMAGE_NAME: thibaultcne/casino:backend
    cmds:
      - docker build -t {{.IMAGE_NAME}} .

  deploy-backend:
    internal: true
    deps: [build-backend]
    dir: backend
    cmds:
      - kubectl apply -f mariadb.yaml
      - kubectl apply -f backend.yaml

  build-frontend:
    internal: true
    dir: frontend
    vars:
      IMAGE_NAME: thibaultcne/casino:frontend
    cmds:
      - docker build -t {{.IMAGE_NAME}} .
    
  deploy-frontend:
    internal: true
    deps: [build-frontend]
    dir: frontend
    cmds:
      - kubectl apply -f frontend.yaml

  deploy:
    cmds:
      - task: deploy-cert-manager
      - task: deploy-letsencrypt
      - task: deploy-traefik
      - task: deploy-backend
      - task: deploy-frontend
  
  rollout:
    deps: [build-backend, build-frontend]
    cmds:
      - kubectl rollout restart deployment/backend -n casino-website
      - kubectl rollout restart deployment/frontend -n casino-website
  