apiVersion: v1
data:
  COOKIE_KEY: casino-website-cookie_key
  COOKIE_NAME: casino-website-cookie-name
  FRONTEND_HOST: localhost
  FRONTEND_PORT: "8080"
  MODE: dev
  MYSQL_DATABASE: casino-website
  MYSQL_HOST: localhost
  MYSQL_PASSWORD: password
  MYSQL_PORT: "3306"
  MYSQL_ROOT_PASSWORD: password
  MYSQL_USER: user
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: api-development-env
  name: development-env
